set(_CATKIN_CURRENT_PACKAGE "cl")
set(cl_VERSION "0.0.0")
set(cl_MAINTAINER "lak <lak@todo.todo>")
set(cl_PACKAGE_FORMAT "2")
set(cl_BUILD_DEPENDS "std_msgs")
set(cl_BUILD_EXPORT_DEPENDS "std_msgs")
set(cl_BUILDTOOL_DEPENDS "catkin")
set(cl_BUILDTOOL_EXPORT_DEPENDS )
set(cl_EXEC_DEPENDS "std_msgs")
set(cl_RUN_DEPENDS "std_msgs")
set(cl_TEST_DEPENDS )
set(cl_DOC_DEPENDS )
set(cl_URL_WEBSITE "")
set(cl_URL_BUGTRACKER "")
set(cl_URL_REPOSITORY "")
set(cl_DEPRECATED "")